# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: swift:latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Swift 5.7.3
      run: wget -q https://download.swift.org/swift-5.7.3-release/ubuntu1804/swift-5.7.3-RELEASE/swift-5.7.3-RELEASE-ubuntu18.04.tar.gz
    - name: Extract Swift 5.7.3
      run: tar xzf swift-5.7.3-RELEASE-ubuntu18.04.tar.gz
    - name: Add Path
      run: echo "::add-path::$GITHUB_WORKSPACE/swift-5.7.3-RELEASE-ubuntu18.04/usr/bin"
    - name: Build
      run: cd wip && swift build
    - name: Run tests
      run: swift test